import '@wisdom-plus/components/base/style'
import '@wisdom-plus/theme-chalk/src/transfer.scss'
import '@wisdom-plus/components/input/style/index'
import '@wisdom-plus/components/button/style/index'
import '@wisdom-plus/components/checkbox/style/index'
import '@wisdom-plus/components/checkbox-group/style/index'
