import '@wisdom-plus/components/base/style'
import '@wisdom-plus/components/input/style/index'
import '@wisdom-plus/components/tag/style/index'
import '@wisdom-plus/components/scrollbar/style/index'
import '@wisdom-plus/components/popper/style/index'
import '@wisdom-plus/theme-chalk/src/select-v2.scss'
