import '@wisdom-plus/components/base/style'
import '@wisdom-plus/theme-chalk/src/table.scss'
import '@wisdom-plus/components/checkbox/style/index'
import '@wisdom-plus/components/tag/style/index'
import '@wisdom-plus/components/tooltip/style/index'
