import '@wisdom-plus/components/base/style/css'
import '@wisdom-plus/theme-chalk/el-date-picker.css'
import '@wisdom-plus/components/input/style/css'
import '@wisdom-plus/components/scrollbar/style/css'
import '@wisdom-plus/components/popper/style/css'
import '@wisdom-plus/components/button/style/css'
