import '@wisdom-plus/components/base/style'
import '@wisdom-plus/theme-chalk/src/cascader-panel.scss'
import '@wisdom-plus/components/checkbox/style/index'
import '@wisdom-plus/components/radio/style/index'
import '@wisdom-plus/components/scrollbar/style/index'
